---
# original defaults
inotify_instances: 128
inotify_watches: 8192

arch_host: nsaserver.pat.sdm.noao.edu
arch_port: 9000
arch_timeout: 11
arch_irods_host: db.pat.sdm.noao.edu
arch_irods_port: 1247
arch_irods_resource: tadaResc
archive_irods331: /noao-tuc-z1/tada/ 
irodsdata: 'puppet:///modules/dmo-hiera/iinit.in'
irodsenv: 'puppet:///modules/dmo-hiera/irodsEnv.dev'

tada_conf: 'puppet:///modules/dmo-hiera/tada-config.yaml'
tada_logging_conf: 'puppet:///modules/dmo-hiera/tada-logging.yaml'
watch_logging_conf: 'puppet:///modules/dmo-hiera/watch-logging.yaml'
dqcli_logging_conf: 'puppet:///modules/dmo-hiera/dqcli-logging.yaml'

localdjango: 'puppet:///modules/dmo-hiera/django_settings_local_pat.py'
#localdjango: 'puppet:///modules/dmo-hiera/django_settings_local_dev.py'
fpacktgz: 'puppet:///modules/tada/fpack-bin-centos-6.6.tgz'
irodstgz: 'puppet:///modules/tada/irods-3.3.1.tgz'
rsyncdconf: 'puppet:///modules/dmo-hiera/rsyncd.conf'
rsyncdscr: 'puppet:///modules/dmo-hiera/rsyncd.scr'
rsyncpwd: 'puppet:///modules/dmo-hiera/rsync.pwd'
udp_recv_channel:
  - port : 8649
    bind : localhost
  - port : 8649
    bind : 0.0.0.0
udp_send_channel:
  - port : 8649
    host : sdmvc.tuc.noao.edu
    ttl  : 2
  - port : 8649
    host : sdmvm1.tuc.noao.edu
    ttl  : 2
tcp_accept_channel:
  - port : 8649

nginx_conf: 'puppet:///modules/dmo-hiera/nginx.conf'
smoke_conf: 'puppet:///modules/dmo-hiera/smoke-config.dev.sh'
mars_vhost: www.mars.noao.edu

mars_host: mars.vagrant.noao.edu
#mars_host: mars1.sdm.noao.edu
mars_port: 8000

#dataqversion: master
#!marsversion: mars-31
#!tadaversion: mars-31
#tadaversion: tada-51

dataqversion: 2.6.2
marsversion: 1.12.0
tadaversion: 2.10.1

djangoserver: /sandbox/mars/start-mars-development.sh
#djangoserver: /sandbox/natica/dev-start.sh

